"""Add history tables

Revision ID: 668be4f92d99
Revises: 
Create Date: 2026-09-07 22:29:10.644327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668be4f92d99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('interaction_type', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_history_id'), 'interaction_history', ['id'], unique=False)
    op.create_index(op.f('ix_interaction_history_patient_id'), 'interaction_history', ['patient_id'], unique=False)
    op.create_index(op.f('ix_interaction_history_session_id'), 'interaction_history', ['session_id'], unique=False)
    op.create_table('risk_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('text_score', sa.Float(), nullable=True),
    sa.Column('voice_score', sa.Float(), nullable=True),
    sa.Column('behaviour_score', sa.Float(), nullable=True),
    sa.Column('structured_score', sa.Float(), nullable=True),
    sa.Column('temporal_score', sa.Float(), nullable=True),
    sa.Column('dds', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.JSON(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_history_id'), 'risk_history', ['id'], unique=False)
    op.create_index(op.f('ix_risk_history_patient_id'), 'risk_history', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_history_patient_id'), table_name='risk_history')
    op.drop_index(op.f('ix_risk_history_id'), table_name='risk_history')
    op.drop_table('risk_history')
    op.drop_index(op.f('ix_interaction_history_session_id'), table_name='interaction_history')
    op.drop_index(op.f('ix_interaction_history_patient_id'), table_name='interaction_history')
    op.drop_index(op.f('ix_interaction_history_id'), table_name='interaction_history')
    op.drop_table('interaction_history')
    # ### end Alembic commands ###
