"""
Therapist Insights Schemas
==========================

Pydantic schemas for the Therapist Clinical Insights / Explainability API (Step 25).

Design Contract:
  - Adapts outputs from the authoritative, frozen MEDHA Explainability Engine
    (`engine/explainability_engine/`).
  - Strict human-in-the-loop framing: all outputs are non-diagnostic,
    support-oriented indicators and observations, never clinical diagnoses.
  - Transparent data provenance: clear distinction between available results,
    missing/insufficient data, and historical trends.
  - Never leaks internal model weights, system paths, or unauthorized case data.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field


class InsightFactorItem(BaseModel):
    """
    Structured contributing factor item generated by the explainability engine.
    """
    factor: str = Field(..., description="High-level descriptive label of the contributing factor")
    description: str = Field(..., description="Support-oriented, non-diagnostic observation")
    type: str = Field(..., description="Factor type (e.g. trend, text, voice, behaviour, structured, temporal, context, activity)")

    model_config = ConfigDict(from_attributes=True)


class InsightActivitySummary(BaseModel):
    """
    Aggregated interaction counts for recent engagement context.
    """
    checkins: int = Field(0, description="Total completed check-ins")
    journal_entries: int = Field(0, description="Total journal entries logged")
    voice_interactions: int = Field(0, description="Total voice records recorded")
    text_interactions: int = Field(0, description="Total chat messages exchanged")

    model_config = ConfigDict(from_attributes=True)


class InsightSignalsSummary(BaseModel):
    """
    Observed specialist distress and risk signals.
    Null indicates the modality prediction is genuinely unavailable.
    """
    text_distress: Optional[float] = Field(None, description="Text distress level (0-100 normalized or null)")
    voice_distress: Optional[float] = Field(None, description="Voice distress level (0-100 normalized or null)")
    behavioural_risk: Optional[float] = Field(None, description="Behavioural risk score (null if blocked or unavailable)")
    structured_risk: Optional[float] = Field(None, description="Structured intake risk score (null if unavailable)")
    temporal_risk: Optional[float] = Field(None, description="Temporal trajectory risk score (null if unavailable)")

    model_config = ConfigDict(from_attributes=True)


class InsightContextSummary(BaseModel):
    """
    Observed case profile and contextual flags.
    """
    threat_event: bool = Field(False, description="Active threat or critical safety event detected")
    protection_issue: bool = Field(False, description="Protection or safety risk identified")
    financial_hardship: bool = Field(False, description="Financial strain reported")
    rehabilitation_issue: bool = Field(False, description="Rehabilitation or medical recovery need identified")
    investigation_delay: bool = Field(False, description="Procedural or investigation delay identified")
    compensation_delay: bool = Field(False, description="Compensation claim delay identified")

    model_config = ConfigDict(from_attributes=True)


class CaseInsightsResponse(BaseModel):
    """
    Comprehensive therapist clinical insights response.
    
    Returned by:
      GET /api/v1/therapist/cases/{case_id}/insights
      GET /api/v1/therapist/sessions/{session_id}/insights
    """
    case_id: uuid.UUID = Field(..., description="Unique case identifier")
    victim_id: str = Field(..., description="External victim identifier")
    session_id: Optional[uuid.UUID] = Field(None, description="Associated session ID if session-specific")
    timepoint: Optional[int] = Field(None, description="Current or assessed timepoint index")
    
    # Status & Availability Sentinels
    results_available: bool = Field(
        ...,
        description="True if prediction/assessment data is available for this case, False otherwise."
    )
    trend_available: bool = Field(
        False,
        description="True if sufficient longitudinal history exists for trend analysis, False if insufficient."
    )
    
    # Assessment summary & risk level
    risk_level: Optional[str] = Field(None, description="Risk level (LOW, MODERATE, HIGH, CRITICAL, or null)")
    triage_level: Optional[str] = Field(None, description="Triage classification (LOW, MEDIUM, HIGH, CRITICAL, UNKNOWN)")
    fused_risk_score: Optional[float] = Field(None, description="Overall fused DDS risk score (0-100)")
    
    # Explainability text & factor breakdown
    summary: str = Field(..., description="Non-diagnostic observational summary for the clinician")
    factors: List[InsightFactorItem] = Field(default_factory=list, description="Categorized contributing factors")
    trend_explanation: str = Field("", description="Longitudinal trend explanation or notice of insufficient history")
    disclaimer: str = Field(
        "This is a support-oriented explanation and is not a medical diagnosis.",
        description="Mandatory clinical decision support disclaimer"
    )
    
    # Contextual breakdowns
    signals: InsightSignalsSummary = Field(default_factory=InsightSignalsSummary, description="Modality signals summary")
    context: InsightContextSummary = Field(default_factory=InsightContextSummary, description="Case context flags")
    recent_activity: InsightActivitySummary = Field(default_factory=InsightActivitySummary, description="Patient engagement counts")
    
    # Audit timestamps
    generated_at: datetime = Field(..., description="Timestamp when the clinical insight was generated")

    model_config = ConfigDict(from_attributes=True)
