"""add behaviour_feature_snapshots table

Revision ID: ead3432ccad1
Revises: efe33f56db5e
Create Date: 2026-09-10 17:16:09.079077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead3432ccad1'
down_revision: Union[str, Sequence[str], None] = 'efe33f56db5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behaviour_feature_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('timepoint', sa.Integer(), nullable=False),
    sa.Column('app_interaction_duration', sa.Float(), nullable=True),
    sa.Column('app_interaction_duration_deviation', sa.Float(), nullable=True),
    sa.Column('checkin_response_delay', sa.Float(), nullable=True),
    sa.Column('checkin_response_delay_deviation', sa.Float(), nullable=True),
    sa.Column('checkin_completion_rate', sa.Float(), nullable=True),
    sa.Column('missed_checkin_count', sa.Float(), nullable=True),
    sa.Column('journal_entry_count', sa.Float(), nullable=True),
    sa.Column('chat_message_count', sa.Float(), nullable=True),
    sa.Column('late_night_usage_ratio', sa.Float(), nullable=True),
    sa.Column('support_resource_access_count', sa.Float(), nullable=True),
    sa.Column('aggregated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'timepoint', name='uix_case_timepoint_behaviour')
    )
    op.create_index(op.f('ix_behaviour_feature_snapshots_case_id'), 'behaviour_feature_snapshots', ['case_id'], unique=False)
    op.create_index(op.f('ix_behaviour_feature_snapshots_timepoint'), 'behaviour_feature_snapshots', ['timepoint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behaviour_feature_snapshots_timepoint'), table_name='behaviour_feature_snapshots')
    op.drop_index(op.f('ix_behaviour_feature_snapshots_case_id'), table_name='behaviour_feature_snapshots')
    op.drop_table('behaviour_feature_snapshots')
    # ### end Alembic commands ###
