"""add raw_events table

Revision ID: efe33f56db5e
Revises: 0427993cb13f
Create Date: 2026-09-10 17:00:36.900268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe33f56db5e'
down_revision: Union[str, Sequence[str], None] = '0427993cb13f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_events_case_id'), 'raw_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_raw_events_event_id'), 'raw_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_raw_events_event_type'), 'raw_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_raw_events_occurred_at'), 'raw_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_raw_events_session_id'), 'raw_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_events_session_id'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_occurred_at'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_event_type'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_event_id'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_case_id'), table_name='raw_events')
    op.drop_table('raw_events')
    # ### end Alembic commands ###
